In [1]:
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [2]:
df_labeled = pd.read_csv('Curn_Supervised.csv')
df_labeled.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Left  
0          1               1        101348.88     1  
1          0               1        112542.58     0  
2          1               0        113931.57     1  
3          0               0         93826.63     0  
4          1               1         79084.10     0

In [3]:
df_labeled.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   CreditScore      50 non-null     int64  
 1   Geography        50 non-null     object 
 2   Gender           50 non-null     object 
 3   Age              50 non-null     int64  
 4   Tenure           50 non-null     int64  
 5   Balance          50 non-null     float64
 6   NumOfProducts    50 non-null     int64  
 7   HasCrCard        50 non-null     int64  
 8   IsActiveMember   50 non-null     int64  
 9   EstimatedSalary  50 non-null     float64
 10  Left             50 non-null     int64  
dtypes: float64(2), int64(7), object(2)
memory usage: 4.4+ KB


In [4]:
df_labeled.Left.unique()

array([1, 0], dtype=int64)

In [5]:
cat_vars=['Geography','Gender','HasCrCard','NumOfProducts','IsActiveMember']
for var in cat_vars:
    cat_list='var'+'_'+var
    cat_list = pd.get_dummies(df_labeled[var], prefix=var)
    df_labeled1=df_labeled.join(cat_list)
    df_labeled=df_labeled1
    
cat_vars=['Geography','Gender','HasCrCard','NumOfProducts','IsActiveMember']
df_labeled_vars=df_labeled.columns.values.tolist()
to_keep=[i for i in df_labeled_vars if i not in cat_vars]

In [6]:
df_labeled_final=df_labeled[to_keep]
df_labeled_final.columns.values

array(['CreditScore', 'Age', 'Tenure', 'Balance', 'EstimatedSalary',
       'Left', 'Geography_France', 'Geography_Germany', 'Geography_Spain',
       'Gender_Female', 'Gender_Male', 'HasCrCard_0', 'HasCrCard_1',
       'NumOfProducts_1', 'NumOfProducts_2', 'NumOfProducts_3',
       'NumOfProducts_4', 'IsActiveMember_0', 'IsActiveMember_1'],
      dtype=object)

In [7]:
from sklearn.ensemble import RandomForestClassifier

In [8]:
X = df_labeled_final.loc[:, df_labeled_final.columns != 'Left']
y = df_labeled_final.loc[:, df_labeled_final.columns == 'Left']

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [11]:
model = RandomForestClassifier()

In [12]:
model.fit(X_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.


RandomForestClassifier()

In [13]:
y_pred = model.predict(X_test)

In [14]:
model.score(X_test,y_test)

0.9411764705882353

In [15]:
import sklearn.metrics as sm

In [16]:
sm.confusion_matrix(y_test, y_pred)

array([[15,  0],
       [ 1,  1]], dtype=int64)

In [17]:
df_unlabeled = pd.read_csv('Curn_Unsupervised.csv')
df_unlabeled.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          698   Germany    Male   44      10  116363.37              2   
1          585   Germany    Male   36       5  146050.97              2   
2          788    France  Female   33       5       0.00              2   
3          655   Germany    Male   41       8  125561.97              1   
4          601   Germany    Male   42       1   98495.72              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               0        198059.16  
1          0               0         86424.57  
2          0               0        116978.19  
3          0               0        164040.94  
4          1               0         40014.76

In [18]:
df_unlabeled.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   CreditScore      1000 non-null   int64  
 1   Geography        1000 non-null   object 
 2   Gender           1000 non-null   object 
 3   Age              1000 non-null   int64  
 4   Tenure           1000 non-null   int64  
 5   Balance          1000 non-null   float64
 6   NumOfProducts    1000 non-null   int64  
 7   HasCrCard        1000 non-null   int64  
 8   IsActiveMember   1000 non-null   int64  
 9   EstimatedSalary  1000 non-null   float64
dtypes: float64(2), int64(6), object(2)
memory usage: 78.2+ KB


In [19]:
cat_vars=['Geography','Gender','HasCrCard','NumOfProducts','IsActiveMember']
for var in cat_vars:
    cat_list='var'+'_'+var
    cat_list = pd.get_dummies(df_unlabeled[var], prefix=var)
    df_unlabeled1=df_unlabeled.join(cat_list)
    df_unlabeled=df_unlabeled1
    
cat_vars=['Geography','Gender','HasCrCard','NumOfProducts','IsActiveMember']
df_unlabeled_vars=df_unlabeled.columns.values.tolist()
to_keep=[i for i in df_unlabeled_vars if i not in cat_vars]

In [20]:
df_unlabeled_final=df_unlabeled[to_keep]
df_unlabeled_final.columns.values

array(['CreditScore', 'Age', 'Tenure', 'Balance', 'EstimatedSalary',
       'Geography_France', 'Geography_Germany', 'Geography_Spain',
       'Gender_Female', 'Gender_Male', 'HasCrCard_0', 'HasCrCard_1',
       'NumOfProducts_1', 'NumOfProducts_2', 'NumOfProducts_3',
       'NumOfProducts_4', 'IsActiveMember_0', 'IsActiveMember_1'],
      dtype=object)

In [21]:
from sklearn.cluster import KMeans

In [22]:
model = KMeans(n_clusters=2)

In [23]:
model.fit(df_unlabeled_final)

KMeans(n_clusters=2)

In [24]:
df_labeled_final['cl'] = model.predict( df_labeled_final.drop(['Left'], axis=1 ) )

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [25]:
df_labeled_final.head(10)

CreditScore  Age  Tenure    Balance  EstimatedSalary  Left  \
0          619   42       2       0.00        101348.88     1   
1          608   41       1   83807.86        112542.58     0   
2          502   42       8  159660.80        113931.57     1   
3          699   39       1       0.00         93826.63     0   
4          850   43       2  125510.82         79084.10     0   
5          645   44       8  113755.78        149756.71     1   
6          822   50       7       0.00         10062.80     0   
7          376   29       4  115046.74        119346.88     1   
8          501   44       4  142051.07         74940.50     0   
9          684   27       2  134603.88         71725.73     0   

   Geography_France  Geography_Germany  Geography_Spain  Gender_Female  \
0                 1                  0                0              1   
1                 0                  0                1              1   
2                 1                  0                0              1   
3                 1                  0                0              1   
4                 0                  0                1              1   
5                 0                  0                1              0   
6                 1                  0                0              0   
7                 0                  1                0              1   
8                 1                  0                0              0   
9                 1                  0                0              0   

   Gender_Male  HasCrCard_0  HasCrCard_1  NumOfProducts_1  NumOfProducts_2  \
0            0            0            1                1                0   
1            0            1            0                1                0   
2            0            0            1                0                0   
3            0            1            0                0                1   
4            0            0            1                1                0   
5            1            0            1                0                1   
6            1            0            1                0                1   
7            0            0            1                0                0   
8            1            1            0                0                1   
9            1            0            1                1                0   

   NumOfProducts_3  NumOfProducts_4  IsActiveMember_0  IsActiveMember_1  cl  
0                0                0                 0                 1   0  
1                0                0                 0                 1   1  
2                1                0                 1                 0   1  
3                0                0                 1                 0   0  
4                0                0                 0                 1   1  
5                0                0                 1                 0   1  
6                0                0                 0                 1   0  
7                0                1                 1                 0   1  
8                0                0                 0                 1   1  
9                0                0                 0                 1   1

In [26]:
pd.crosstab( df_labeled_final.Left , df_labeled_final.cl )

cl     0   1
Left        
0     20  18
1      3   9

In [27]:
df_unlabeled_final['Left'] = model.labels_
df_unlabeled_final.head()

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


CreditScore  Age  Tenure    Balance  EstimatedSalary  Geography_France  \
0          698   44      10  116363.37        198059.16                 0   
1          585   36       5  146050.97         86424.57                 0   
2          788   33       5       0.00        116978.19                 1   
3          655   41       8  125561.97        164040.94                 0   
4          601   42       1   98495.72         40014.76                 0   

   Geography_Germany  Geography_Spain  Gender_Female  Gender_Male  \
0                  1                0              0            1   
1                  1                0              0            1   
2                  0                0              1            0   
3                  1                0              0            1   
4                  1                0              0            1   

   HasCrCard_0  HasCrCard_1  NumOfProducts_1  NumOfProducts_2  \
0            0            1                0                1   
1            1            0                0                1   
2            1            0                0                1   
3            1            0                1                0   
4            0            1                1                0   

   NumOfProducts_3  NumOfProducts_4  IsActiveMember_0  IsActiveMember_1  Left  
0                0                0                 1                 0     1  
1                0                0                 1                 0     1  
2                0                0                 1                 0     0  
3                0                0                 1                 0     1  
4                0                0                 1                 0     1

In [28]:
model = RandomForestClassifier()

In [29]:
X_train = df_unlabeled_final.drop(['Left'],axis=1)

In [30]:
y_train = df_unlabeled_final.Left

In [31]:
X_test = df_labeled_final.drop(['Left','cl'],axis=1)

In [32]:
y_test = df_labeled_final.Left

In [33]:
model.fit(X_train,y_train)

RandomForestClassifier()

In [34]:
y_pred = model.predict(X_test)

In [35]:
model.score(X_test,y_test)

0.58

In [36]:
sm.confusion_matrix(y_test, y_pred)

array([[20, 18],
       [ 3,  9]], dtype=int64)